numProcs   = 1
LocalTimes = {}
LocalFlops = {}
LocalMessageLens = {}
LocalMessages = {}
LocalReductions = {}
LocalObjects = {}
LocalMemory = {}
Stages = {}
Stages["Main Stage"] = {}
Stages["Main Stage"]["summary"] = {}
Stages["Main Stage"]["MatMult MF"] = {}
Stages["Main Stage"]["MatMult"] = {}
Stages["Main Stage"]["MatMults"] = {}
Stages["Main Stage"]["MatMultConstr"] = {}
Stages["Main Stage"]["MatMultAdd"] = {}
Stages["Main Stage"]["MatMultTranspose"] = {}
Stages["Main Stage"]["MatMultTrConstr"] = {}
Stages["Main Stage"]["MatMultTrAdd"] = {}
Stages["Main Stage"]["MatSolve"] = {}
Stages["Main Stage"]["MatSolves"] = {}
Stages["Main Stage"]["MatSolveAdd"] = {}
Stages["Main Stage"]["MatSolveTranspos"] = {}
Stages["Main Stage"]["MatSolveTrAdd"] = {}
Stages["Main Stage"]["MatSOR"] = {}
Stages["Main Stage"]["MatForwardSolve"] = {}
Stages["Main Stage"]["MatBackwardSolve"] = {}
Stages["Main Stage"]["MatLUFactor"] = {}
Stages["Main Stage"]["MatLUFactorSym"] = {}
Stages["Main Stage"]["MatLUFactorNum"] = {}
Stages["Main Stage"]["MatCholeskyFctr"] = {}
Stages["Main Stage"]["MatCholFctrSym"] = {}
Stages["Main Stage"]["MatCholFctrNum"] = {}
Stages["Main Stage"]["MatILUFactor"] = {}
Stages["Main Stage"]["MatILUFactorSym"] = {}
Stages["Main Stage"]["MatICCFactorSym"] = {}
Stages["Main Stage"]["MatCopy"] = {}
Stages["Main Stage"]["MatConvert"] = {}
Stages["Main Stage"]["MatScale"] = {}
Stages["Main Stage"]["MatResidual"] = {}
Stages["Main Stage"]["MatAssemblyBegin"] = {}
Stages["Main Stage"]["MatAssemblyEnd"] = {}
Stages["Main Stage"]["MatSetValues"] = {}
Stages["Main Stage"]["MatGetValues"] = {}
Stages["Main Stage"]["MatGetRow"] = {}
Stages["Main Stage"]["MatGetRowIJ"] = {}
Stages["Main Stage"]["MatGetSubMatrice"] = {}
Stages["Main Stage"]["MatGetSubMatrix"] = {}
Stages["Main Stage"]["MatGetOrdering"] = {}
Stages["Main Stage"]["MatIncreaseOvrlp"] = {}
Stages["Main Stage"]["MatPartitioning"] = {}
Stages["Main Stage"]["MatCoarsen"] = {}
Stages["Main Stage"]["MatZeroEntries"] = {}
Stages["Main Stage"]["MatLoad"] = {}
Stages["Main Stage"]["MatView"] = {}
Stages["Main Stage"]["MatAXPY"] = {}
Stages["Main Stage"]["MatFDColorCreate"] = {}
Stages["Main Stage"]["MatFDColorSetUp"] = {}
Stages["Main Stage"]["MatFDColorApply"] = {}
Stages["Main Stage"]["MatFDColorFunc"] = {}
Stages["Main Stage"]["MatTranspose"] = {}
Stages["Main Stage"]["MatMatMult"] = {}
Stages["Main Stage"]["MatMatSolve"] = {}
Stages["Main Stage"]["MatMatMultSym"] = {}
Stages["Main Stage"]["MatMatMultNum"] = {}
Stages["Main Stage"]["MatMatMatMult"] = {}
Stages["Main Stage"]["MatMatMatMultSym"] = {}
Stages["Main Stage"]["MatMatMatMultNum"] = {}
Stages["Main Stage"]["MatPtAP"] = {}
Stages["Main Stage"]["MatPtAPSymbolic"] = {}
Stages["Main Stage"]["MatPtAPNumeric"] = {}
Stages["Main Stage"]["MatRARt"] = {}
Stages["Main Stage"]["MatRARtSym"] = {}
Stages["Main Stage"]["MatRARtNum"] = {}
Stages["Main Stage"]["MatMatTransMult"] = {}
Stages["Main Stage"]["MatMatTrnMultSym"] = {}
Stages["Main Stage"]["MatMatTrnMultNum"] = {}
Stages["Main Stage"]["MatTrnMatMult"] = {}
Stages["Main Stage"]["MatTrnMatMultSym"] = {}
Stages["Main Stage"]["MatTrnMatMultNum"] = {}
Stages["Main Stage"]["MatTrnColorCreate"] = {}
Stages["Main Stage"]["MatRedundantMat"] = {}
Stages["Main Stage"]["MatGetSeqNZStrct"] = {}
Stages["Main Stage"]["MatGetMultiProcBlock"] = {}
Stages["Main Stage"]["MatMPISumSeqNumeric"] = {}
Stages["Main Stage"]["MatMPISumSeqSymbolic"] = {}
Stages["Main Stage"]["MatMPISumSeq"] = {}
Stages["Main Stage"]["MatMPIConcateSeq"] = {}
Stages["Main Stage"]["MatGetLocalMat"] = {}
Stages["Main Stage"]["MatGetLocalMatCondensed"] = {}
Stages["Main Stage"]["MatGetBrowsOfAcols"] = {}
Stages["Main Stage"]["MatGetBrAoCol"] = {}
Stages["Main Stage"]["MatApplyPAPt_Symbolic"] = {}
Stages["Main Stage"]["MatApplyPAPt_Numeric"] = {}
Stages["Main Stage"]["MatApplyPAPt"] = {}
Stages["Main Stage"]["MatGetSymTrans"] = {}
Stages["Main Stage"]["MatGetSymTransR"] = {}
Stages["Main Stage"]["MatTranspose_SeqAIJ_FAST"] = {}
Stages["Main Stage"]["MatCUSPCopyTo"] = {}
Stages["Main Stage"]["MatCUSPARSECopyTo"] = {}
Stages["Main Stage"]["MatViennaCLCopyTo"] = {}
Stages["Main Stage"]["MatSetValBatch"] = {}
Stages["Main Stage"]["MatSetValBatch1"] = {}
Stages["Main Stage"]["MatSetValBatch2"] = {}
Stages["Main Stage"]["MatSetValBatch3"] = {}
Stages["Main Stage"]["MatSetValBatch4"] = {}
Stages["Main Stage"]["MatColoringApply"] = {}
Stages["Main Stage"]["MatColoringComm"] = {}
Stages["Main Stage"]["MatColoringLocal"] = {}
Stages["Main Stage"]["MatColoringIS"] = {}
Stages["Main Stage"]["MatColoringSetUp"] = {}
Stages["Main Stage"]["MatColoringWeights"] = {}
Stages["Main Stage"]["VecView"] = {}
Stages["Main Stage"]["VecMax"] = {}
Stages["Main Stage"]["VecMin"] = {}
Stages["Main Stage"]["VecDotBarrier"] = {}
Stages["Main Stage"]["VecDot"] = {}
Stages["Main Stage"]["VecDotNormBarr"] = {}
Stages["Main Stage"]["VecDotNorm2"] = {}
Stages["Main Stage"]["VecMDotBarrier"] = {}
Stages["Main Stage"]["VecMDot"] = {}
Stages["Main Stage"]["VecTDot"] = {}
Stages["Main Stage"]["VecMTDot"] = {}
Stages["Main Stage"]["VecNormBarrier"] = {}
Stages["Main Stage"]["VecNorm"] = {}
Stages["Main Stage"]["VecScale"] = {}
Stages["Main Stage"]["VecCopy"] = {}
Stages["Main Stage"]["VecSet"] = {}
Stages["Main Stage"]["VecAXPY"] = {}
Stages["Main Stage"]["VecAYPX"] = {}
Stages["Main Stage"]["VecAXPBYCZ"] = {}
Stages["Main Stage"]["VecWAXPY"] = {}
Stages["Main Stage"]["VecMAXPY"] = {}
Stages["Main Stage"]["VecSwap"] = {}
Stages["Main Stage"]["VecOps"] = {}
Stages["Main Stage"]["VecAssemblyBegin"] = {}
Stages["Main Stage"]["VecAssemblyEnd"] = {}
Stages["Main Stage"]["VecPointwiseMult"] = {}
Stages["Main Stage"]["VecSetValues"] = {}
Stages["Main Stage"]["VecLoad"] = {}
Stages["Main Stage"]["VecScatterBarrie"] = {}
Stages["Main Stage"]["VecScatterBegin"] = {}
Stages["Main Stage"]["VecScatterEnd"] = {}
Stages["Main Stage"]["VecSetRandom"] = {}
Stages["Main Stage"]["VecReduceArith"] = {}
Stages["Main Stage"]["VecReduceBarrier"] = {}
Stages["Main Stage"]["VecReduceComm"] = {}
Stages["Main Stage"]["VecReduceBegin"] = {}
Stages["Main Stage"]["VecReduceEnd"] = {}
Stages["Main Stage"]["VecNormalize"] = {}
Stages["Main Stage"]["KSPGMRESOrthog"] = {}
Stages["Main Stage"]["KSPSetUp"] = {}
Stages["Main Stage"]["KSPSolve"] = {}
Stages["Main Stage"]["PCGAMGGraph_AGG"] = {}
Stages["Main Stage"]["PCGAMGGraph_GEO"] = {}
Stages["Main Stage"]["PCGAMGCoarse_AGG"] = {}
Stages["Main Stage"]["PCGAMGCoarse_GEO"] = {}
Stages["Main Stage"]["PCGAMGProl_AGG"] = {}
Stages["Main Stage"]["PCGAMGProl_GEO"] = {}
Stages["Main Stage"]["PCGAMGPOpt_AGG"] = {}
Stages["Main Stage"]["GAMG: createProl"] = {}
Stages["Main Stage"]["  Graph"] = {}
Stages["Main Stage"]["  MIS/Agg"] = {}
Stages["Main Stage"]["  geo: growSupp"] = {}
Stages["Main Stage"]["  geo: triangle"] = {}
Stages["Main Stage"]["    search&set"] = {}
Stages["Main Stage"]["  SA: col data"] = {}
Stages["Main Stage"]["  SA: frmProl0"] = {}
Stages["Main Stage"]["  SA: smooth"] = {}
Stages["Main Stage"]["GAMG: partLevel"] = {}
Stages["Main Stage"]["  repartition"] = {}
Stages["Main Stage"]["  Invert-Sort"] = {}
Stages["Main Stage"]["  Move A"] = {}
Stages["Main Stage"]["  Move P"] = {}
Stages["Main Stage"]["PCSetUp"] = {}
Stages["Main Stage"]["PCSetUpOnBlocks"] = {}
Stages["Main Stage"]["PCApplyOnBlocks"] = {}
Stages["Main Stage"]["PCApplyOnMproc"] = {}
Stages["Main Stage"]["PCApply"] = {}
Stages["Main Stage"]["PCApplyCoarse"] = {}
Stages["Main Stage"]["PCApplyMultiple"] = {}
Stages["Main Stage"]["PCApplySymmLeft"] = {}
Stages["Main Stage"]["PCApplySymmRight"] = {}
Stages["Main Stage"]["PCModifySubMatri"] = {}
Stages["Main Stage"]["KSPSolve_FS_0"] = {}
Stages["Main Stage"]["KSPSolve_FS_1"] = {}
Stages["Main Stage"]["KSPSolve_FS_2"] = {}
Stages["Main Stage"]["KSPSolve_FS_3"] = {}
Stages["Main Stage"]["KSPSolve_FS_4"] = {}
Stages["Main Stage"]["KSPSolve_FS_Schu"] = {}
Stages["Main Stage"]["KSPSolve_FS_Up"] = {}
Stages["Main Stage"]["KSPSolve_FS_Low"] = {}
LocalTimes[0] = 0.638928
LocalFlops[0] = 5.20413e+08
LocalMessageLens[0] = 0.
LocalMessages[0] = 0.
LocalReductions[0] = 0.
LocalObjects[0] = 0.
LocalMemory[0] = 0.
Stages["Main Stage"]["summary"][0] = {"time" : 0.638919, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 5.20413e+08}
Stages["Main Stage"]["MatMult MF"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMult"][0] = {"count" : 651, "time" : 0.0454789, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 1.17784e+08}
Stages["Main Stage"]["MatMults"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMultConstr"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMultAdd"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMultTranspose"][0] = {"count" : 624, "time" : 0.0703535, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 1.16659e+08}
Stages["Main Stage"]["MatMultTrConstr"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMultTrAdd"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSolve"][0] = {"count" : 626, "time" : 0.0553567, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 1.1476e+08}
Stages["Main Stage"]["MatSolves"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSolveAdd"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSolveTranspos"][0] = {"count" : 626, "time" : 0.0808001, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 1.1476e+08}
Stages["Main Stage"]["MatSolveTrAdd"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSOR"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatForwardSolve"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatBackwardSolve"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatLUFactor"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatLUFactorSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatLUFactorNum"][0] = {"count" : 27, "time" : 0.0184854, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 2.22141e+07}
Stages["Main Stage"]["MatCholeskyFctr"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatCholFctrSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatCholFctrNum"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatILUFactor"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatILUFactorSym"][0] = {"count" : 27, "time" : 0.00869283, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatICCFactorSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatCopy"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatConvert"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatScale"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatResidual"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatAssemblyBegin"][0] = {"count" : 27, "time" : 4.38746e-06, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatAssemblyEnd"][0] = {"count" : 27, "time" : 0.00189552, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSetValues"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetValues"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetRow"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetRowIJ"][0] = {"count" : 27, "time" : 9.10554e-06, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetSubMatrice"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetSubMatrix"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetOrdering"][0] = {"count" : 27, "time" : 0.00104474, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatIncreaseOvrlp"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatPartitioning"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatCoarsen"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatZeroEntries"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatLoad"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatView"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatAXPY"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatFDColorCreate"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatFDColorSetUp"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatFDColorApply"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatFDColorFunc"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatTranspose"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatMult"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatSolve"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatMultSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatMultNum"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatMatMult"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatMatMultSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatMatMultNum"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatPtAP"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatPtAPSymbolic"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatPtAPNumeric"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatRARt"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatRARtSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatRARtNum"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatTransMult"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatTrnMultSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMatTrnMultNum"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatTrnMatMult"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatTrnMatMultSym"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatTrnMatMultNum"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatTrnColorCreate"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatRedundantMat"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetSeqNZStrct"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetMultiProcBlock"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMPISumSeqNumeric"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMPISumSeqSymbolic"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMPISumSeq"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatMPIConcateSeq"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetLocalMat"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetLocalMatCondensed"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetBrowsOfAcols"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetBrAoCol"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatApplyPAPt_Symbolic"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatApplyPAPt_Numeric"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatApplyPAPt"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetSymTrans"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatGetSymTransR"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatTranspose_SeqAIJ_FAST"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatCUSPCopyTo"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatCUSPARSECopyTo"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatViennaCLCopyTo"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSetValBatch"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSetValBatch1"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSetValBatch2"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSetValBatch3"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatSetValBatch4"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatColoringApply"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatColoringComm"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatColoringLocal"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatColoringIS"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatColoringSetUp"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["MatColoringWeights"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecView"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecMax"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecMin"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecDotBarrier"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecDot"][0] = {"count" : 1248, "time" : 0.00641956, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 8.53498e+06}
Stages["Main Stage"]["VecDotNormBarr"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecDotNorm2"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecMDotBarrier"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecMDot"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecTDot"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecMTDot"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecNormBarrier"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecNorm"][0] = {"count" : 678, "time" : 0.0033458, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 4.55437e+06}
Stages["Main Stage"]["VecScale"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecCopy"][0] = {"count" : 77, "time" : 9.84184e-05, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecSet"][0] = {"count" : 2092, "time" : 0.0023461, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecAXPY"][0] = {"count" : 1872, "time" : 0.0144024, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 1.28043e+07}
Stages["Main Stage"]["VecAYPX"][0] = {"count" : 1225, "time" : 0.00214591, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 8.34198e+06}
Stages["Main Stage"]["VecAXPBYCZ"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecWAXPY"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecMAXPY"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecSwap"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecOps"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecAssemblyBegin"][0] = {"count" : 27, "time" : 2.03867e-06, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecAssemblyEnd"][0] = {"count" : 27, "time" : 1.63913e-06, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecPointwiseMult"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecSetValues"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecLoad"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecScatterBarrie"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecScatterBegin"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecScatterEnd"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecSetRandom"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecReduceArith"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecReduceBarrier"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecReduceComm"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecReduceBegin"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecReduceEnd"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["VecNormalize"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPGMRESOrthog"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSetUp"][0] = {"count" : 54, "time" : 0.000707191, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve"][0] = {"count" : 27, "time" : 0.315864, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 5.20413e+08}
Stages["Main Stage"]["PCGAMGGraph_AGG"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCGAMGGraph_GEO"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCGAMGCoarse_AGG"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCGAMGCoarse_GEO"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCGAMGProl_AGG"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCGAMGProl_GEO"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCGAMGPOpt_AGG"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["GAMG: createProl"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  Graph"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  MIS/Agg"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  geo: growSupp"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  geo: triangle"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["    search&set"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  SA: col data"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  SA: frmProl0"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  SA: smooth"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["GAMG: partLevel"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  repartition"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  Invert-Sort"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  Move A"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["  Move P"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCSetUp"][0] = {"count" : 54, "time" : 0.0295912, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 2.22141e+07}
Stages["Main Stage"]["PCSetUpOnBlocks"][0] = {"count" : 27, "time" : 0.0286127, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 2.22141e+07}
Stages["Main Stage"]["PCApplyOnBlocks"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCApplyOnMproc"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCApply"][0] = {"count" : 1252, "time" : 0.142106, "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 2.29521e+08}
Stages["Main Stage"]["PCApplyCoarse"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCApplyMultiple"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCApplySymmLeft"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCApplySymmRight"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["PCModifySubMatri"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_0"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_1"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_2"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_3"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_4"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_Schu"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_Up"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
Stages["Main Stage"]["KSPSolve_FS_Low"][0] = {"count" : 0, "time" : 0., "numMessages" : 0., "messageLength" : 0., "numReductions" : 0., "flops" : 0.}
